# -*- coding: utf-8 -*-
"""정올 문제풀이.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13_IAADYWfdehBpGsZnhzpyZburRIT3Yp
"""

num1 = 10
num2 = 20
num3 = 30

print(num1,"+",num2,"=",num3)

num1 = 80.5
num2 = 22.34
num3 = 102.84

print(num1,num2,num3)

num1 = 10.5
num2 = 50

print(num1,"*",num2,"=",num1*num2)

num = int(input())
num1 = int(input())
num2 = int(input())

print("sum =",num+num1+num2)
print("avg =",(num+num1+num2)//3 )

#print("yard?")
y = float(input("yard? "))

print(y,"yard =",y*91.44,"cm")